import { config } from '../config';

const fse = require('fs-extra');

const getBlueprintFileContent = (stringifiedBlueprint: string) => {
    return `
# Warning: **Do not edit this file directly**

# Info
- See the README.md to know how to generate a new blueprint
- Copy the json below to update the blueprint attribute in the relevant UsecaseConfig entity
---

${stringifiedBlueprint}
`;
};

const moveBlueprintFile = (from, to) => {
    fse.move(from, to, { overwrite: true }, (err) => {
        if (err) return console.error(err);
        console.log('Blueprint moved to: ', to);
    });
};

const generateBlueprintFile = (stringifiedBlueprint: string, from, to) => {
    fse.writeFile(config.blueprintFileName, getBlueprintFileContent(stringifiedBlueprint), function (err) {
        if (err) throw err;
        console.log('Blueprint Saved');
        moveBlueprintFile(from, to);
    });
};

export { generateBlueprintFile };
