import { StellioTemplate } from 'src/interfaces';

const entityType = 'Process';
const entityTypeTitle = 'Process';

const template: StellioTemplate = {
    id: `urn:ngsi-ld:${entityType}:Template`,
    type: 'Template',
    name: {
        type: 'Property',
        value: 'Placeholder',
        jsonSchema: {
            type: 'Property',
            value: { schemaType: 'string', title: `Name of the ${entityTypeTitle}`, friendlyAttributeName: 'Name' },
        },
    },
    generates: {
        type: 'Relationship',
        object: 'urn:ngsi-ld:Product:Template',
        jsonSchema: {
            type: 'Property',
            value: {
                schemaType: 'array',
                friendlyAttributeName: 'Generated Products',
                title: `What Products were generated by this ${entityTypeTitle}?`,
                items: {
                    schemaType: 'string',
                    format: 'uri',
                    title: `Pick a Product`,
                },
            },
        },
    },
    uses: {
        type: 'Relationship',
        object: 'urn:ngsi-ld:Product:Template',
        jsonSchema: {
            type: 'Property',
            value: {
                schemaType: 'array',
                friendlyAttributeName: 'Used Products',
                title: `What Products were used by this ${entityTypeTitle}?`,
                items: {
                    schemaType: 'string',
                    format: 'uri',
                    title: `Pick a Product`,
                },
            },
        },
    },
    jsonSchema: {
        type: 'Property',
        value: {
            schemaType: entityType,
            title: entityTypeTitle,
            minimum: 0,
            required: ['name'],
            description: `The ${entityTypeTitle} of a Transformation. A new process is created for each transformation cycle and it contains Products used and generated during this particular cycle`,
        },
    },
};

export default template;
