import { StellioTemplate } from 'src/interfaces';

const entityType = 'Product';
const entityTypeTitle = 'Product';

const template: StellioTemplate = {
    id: `urn:ngsi-ld:${entityType}:Template`,
    type: 'Template',
    name: {
        type: 'Property',
        value: 'Placeholder',
        jsonSchema: {
            type: 'Property',
            value: { schemaType: 'string', title: `Name of the ${entityTypeTitle}`, friendlyAttributeName: 'Name' },
        },
    },
    imageSrc: {
        type: 'Property',
        value: 'Image',
        jsonSchema: {
            type: 'Property',
            value: { schemaType: 'string', title: `Path to the image`, friendlyAttributeName: 'Image' },
        },
    },
    mass: {
        type: 'Property',
        value: 1,
        jsonSchema: {
            type: 'Property',
            value: {
                schemaType: 'integer',
                title: `Amount of matter`,
                friendlyAttributeName: 'Amount of matter',
                canSetUnitCode: true,
            },
        },
    },
    isCarriedBy: {
        type: 'Relationship',
        object: 'urn:ngsi-ld:Transporter:Template',
        jsonSchema: {
            type: 'Property',
            value: {
                schemaType: 'string',
                format: 'uri',
                title: `This ${entityTypeTitle} is carried by which transporter?`,
                friendlyAttributeName: 'Carried by',
                canSetObservedAt: true,
            },
        },
    },
    isUsedBy: {
        type: 'Relationship',
        object: 'urn:ngsi-ld:Transformation:Template',
        jsonSchema: {
            type: 'Property',
            value: {
                schemaType: 'string',
                format: 'uri',
                title: `This ${entityTypeTitle} is used as input by which Transformation?`,
                friendlyAttributeName: 'Used by',
                canSetObservedAt: true,
            },
        },
    },
    isGeneratedBy: {
        type: 'Relationship',
        object: 'urn:ngsi-ld:Transformation:Template',
        jsonSchema: {
            type: 'Property',
            value: {
                schemaType: 'string',
                format: 'uri',
                title: `This ${entityTypeTitle} is generated as output by which Transformation?`,
                friendlyAttributeName: 'Generated by',
                canSetObservedAt: true,
            },
        },
    },
    isStoredIn: {
        type: 'Relationship',
        object: 'List:of:template',
        jsonSchema: {
            type: 'Property',
            value: {
                schemaType: 'string',
                format: 'uri',
                title: `What's the last known storage location of this ${entityTypeTitle}?`,
                friendlyAttributeName: 'Last known storage location',
                listOfAllowedRelationships: ['urn:ngsi-ld:Storage:Template', 'urn:ngsi-ld:ProductionSystem:Template'],
            },
        },
    },
    jsonSchema: {
        type: 'Property',
        value: {
            schemaType: entityType,
            title: entityTypeTitle,
            minimum: 1,
            required: ['name'],
            description: `This is a product. It can be anything, a raw material, a chemical, an object...`,
        },
    },
};

export default template;
