import { LotusSensor } from './lotusSensor';
import { UltraSonicFlowMeter } from './ultraSonicFlowMeter';
import { FlowMeter } from './flowMeter';
import { Bypass } from './bypass';
import { PressureGauge } from './pressureGauge';
import { LotusBox } from './lotusBox';

const fse = require('fs-extra');

const blueprint = [LotusSensor, UltraSonicFlowMeter, FlowMeter, Bypass, PressureGauge, LotusBox];
const stringifiedBlueprint = JSON.stringify(blueprint);
const FILE_NAME = 'blueprint.md';

fse.writeFile(
    FILE_NAME,
    `
# Warning: **Do not edit this file directly**

# Info
- See the README.md to know how to generate a new blueprint
- Copy the json below to update the blueprint attribute in the relevant UsecaseConfig entity
---

${stringifiedBlueprint}
`,
    function (err) {
        if (err) throw err;
        console.log('Blueprint Saved');

        const SPECIFIC_USECASE_PATH = __dirname.split('dist\\')[1];
        const from = `./${FILE_NAME}`;
        const to = `../../../${SPECIFIC_USECASE_PATH}/${FILE_NAME}`;
        fse.move(from, to, { overwrite: true }, (err) => {
            if (err) return console.error(err);
            console.log('Blueprint moved to: ', to);
        });
    }
);
